CREATE OR REPLACE DATABASE flight_dwh;

USE DATABASE flight_dwh;


CREATE OR REPLACE SCHEMA stage;
CREATE OR REPLACE SCHEMA transform;
CREATE OR REPLACE SCHEMA mart;
CREATE OR REPLACE SCHEMA audit;


CREATE OR REPLACE FILE FORMAT stage.csv_format
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '');


CREATE OR REPLACE STAGE stage.flight_stage
FILE_FORMAT = stage.csv_format;